packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: "^6.0.2"

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  argon2: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
