import type { Metadata } from "next";
import { cookies } from "next/headers";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import "./globals.css";
import { Frame } from "@/components/layout/frame";
import { Loader } from "@/lib/loading";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: {
    template: "%s | Next",
    default: "Next",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = await cookies();
  const locale = store.get("locale")?.value || "en";

  return (
    <html
      lang={locale}
      className={cn("h-full antialiased", "font-sans")}
      suppressHydrationWarning
    >
      <body className="min-h-full">
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <Loader />
            <Toaster
              richColors
              position="top-center"
              toastOptions={{
                classNames: {
                  closeButton: "!right-0 !left-auto !translate-x-1/2",
                },
              }}
            />
            <Frame>{children}</Frame>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
