export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  CNY: "¥",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  KRW: "₩",
  INR: "₹",
  RUB: "₽",
  BRL: "R$",
  AUD: "A$",
  CAD: "C$",
  HKD: "HK$",
  SGD: "S$",
  TWD: "NT$",
  CHF: "Fr",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "zł",
  TRY: "₺",
  MXN: "$",
  ZAR: "R",
  NZD: "NZ$",
  THB: "฿",
  IDR: "Rp",
  MYR: "RM",
  PHP: "₱",
  VND: "₫",
  UAH: "₴",
  CZK: "Kč",
  HUF: "Ft",
  ILS: "₪",
  AED: "د.إ",
  SAR: "﷼",
};

export function currencySymbol(code: string): string {
  return CURRENCY_SYMBOLS[code.toUpperCase()] ?? code;
}
