//
//  EmojiSearchIndex.swift
//  Qianlai
//

import Foundation

/// Keyword index powering the icon picker's search: zh terms first plus
/// common English aliases per icon. There is no public emoji-metadata API,
/// so this table is the search — every catalog icon must have an entry and
/// every entry must name a catalog icon (both enforced by tests).
enum EmojiSearch {
    static let keywords: [String: String] = [
        // 常用
        "💰": "钱袋 money 钱 金钱 财富",
        "💳": "信用卡 credit 银行卡 刷卡 支付",
        "👛": "钱包 wallet 皮夹",
        "👜": "手提包 handbag 包 皮包",
        "💵": "美元 dollar 现金 钞票 纸币",
        "💴": "日元 yen 现金 钞票 纸币",
        "💶": "欧元 euro 现金 钞票 纸币",
        "💷": "英镑 pound 现金 钞票 纸币",
        "🪙": "硬币 coin 零钱",
        "💎": "钻石 diamond 宝石 珠宝",
        "🧾": "收据 receipt 发票 账单 小票",
        "🧮": "算盘 abacus 计算器 计算",
        "🏦": "银行 bank",
        "💱": "货币兑换 exchange 换汇 兑换",
        "🏧": "取款机 atm 自助银行 取款",
        "💲": "美元符号 dollar 美元",
        // 餐饮
        "🍜": "面条 noodle 拉面 米线 汤面",
        "🍚": "米饭 rice 白米饭",
        "🍿": "爆米花 popcorn",
        "🍎": "苹果 apple 水果",
        "🥬": "蔬菜 vegetable 青菜 绿叶菜 生菜",
        "🍕": "披萨 pizza",
        "🍔": "汉堡 burger hamburger",
        "🍣": "寿司 sushi",
        "🍰": "蛋糕 cake 甜点",
        "🍦": "冰淇淋 ice cream 雪糕 冰激凌",
        "☕": "咖啡 coffee 咖啡厅",
        "🍺": "啤酒 beer 酒 酒吧",
        "🍵": "茶 tea 喝茶",
        "🥤": "饮料 drink 可乐 塑料杯",
        "🍱": "便当 bento 盒饭",
        "🍲": "火锅 hotpot 炖菜 汤锅",
        "🍞": "面包 bread 吐司",
        "🥐": "牛角包 croissant 可颂 面包",
        "🥖": "法棍 baguette 面包",
        "🥨": "碱水面包 pretzel 椒盐卷饼",
        "🧀": "奶酪 cheese 芝士",
        "🍳": "煎蛋 egg 荷包蛋 炒蛋",
        "🥓": "培根 bacon",
        "🍖": "肉 meat 炖肉 骨头肉",
        "🍗": "鸡腿 chicken 炸鸡",
        "🌭": "热狗 hotdog",
        "🌮": "塔可 taco 墨西哥卷",
        "🌯": "卷饼 burrito 墨西哥卷",
        "🥗": "沙拉 salad 蔬菜沙拉",
        "🍝": "意面 pasta 意大利面",
        "🍩": "甜甜圈 donut doughnut",
        "🍪": "曲奇 cookie 饼干",
        "🎂": "生日蛋糕 birthday cake 蛋糕 生日",
        "🍫": "巧克力 chocolate",
        "🍬": "糖果 candy 糖",
        "🧋": "奶茶 bubble tea 珍珠奶茶",
        // 交通
        "🚌": "公交车 bus 公共汽车 巴士",
        "✈️": "飞机 airplane flight 机票 航班",
        "🚗": "汽车 car 轿车 开车",
        "🚕": "出租车 taxi 的士 打车",
        "🚙": "越野车 suv 汽车",
        "🚄": "高铁 high-speed train 动车 高速列车",
        "⛴️": "轮渡 ferry 船 渡轮",
        "🚲": "自行车 bicycle 骑车 单车",
        "🛵": "电动车 scooter 踏板摩托 小摩托",
        "⛽": "加油站 gas 加油 油",
        "🅿️": "停车 parking 停车场",
        "🚏": "公交站 bus stop 车站 站牌",
        "🚦": "红绿灯 traffic light 信号灯",
        "🛫": "起飞 departure 出发 航班",
        "🚂": "火车 train 蒸汽火车",
        "🚆": "火车 train 列车",
        "🚇": "地铁 subway metro",
        "🚊": "有轨电车 tram 电车",
        "🚉": "车站 station 火车站",
        "🚁": "直升机 helicopter",
        "🛶": "皮划艇 canoe 独木舟 小船",
        "🚤": "快艇 speedboat 小艇",
        "🛳️": "邮轮 cruise 客轮 大船",
        "🛴": "滑板车 scooter 踏板车",
        "🚐": "面包车 van 商务车",
        "🏍️": "摩托车 motorcycle 机车",
        "🗺️": "地图 map 导航",
        "🧳": "行李 luggage 行李箱 旅行",
        // 购物
        "👕": "T恤 tshirt 上衣 衣服",
        "🎊": "礼花 confetti 庆祝 派对",
        "🛍️": "购物袋 shopping 逛街 买",
        "🎁": "礼物 gift present",
        "👟": "运动鞋 sneaker 鞋 球鞋",
        "💄": "口红 lipstick 化妆 美妆",
        "🧴": "洗护 lotion 乳液 日化 瓶子",
        "🧼": "肥皂 soap 清洁 洗涤",
        "👗": "连衣裙 dress 裙子",
        "👖": "裤子 pants 牛仔裤",
        "🧥": "外套 coat 夹克",
        "👔": "领带 tie 正装",
        "🥾": "靴子 boot 登山鞋 鞋",
        "👒": "草帽 hat 遮阳帽 帽子",
        "🧢": "棒球帽 cap 鸭舌帽 帽子",
        "🎒": "背包 backpack 双肩包",
        "👑": "王冠 crown 皇冠",
        "🕶️": "墨镜 sunglasses 太阳镜",
        "💍": "戒指 ring 首饰 婚戒",
        "🩳": "短裤 shorts",
        // 居住
        "🏠": "房子 home 房屋 家",
        "🍼": "奶瓶 baby bottle 婴儿 母婴",
        "🛋️": "沙发 sofa couch",
        "🛏️": "床 bed 睡觉",
        "🚿": "淋浴 shower 洗澡 花洒",
        "🚽": "马桶 toilet 厕所 卫生间",
        "🔧": "扳手 wrench 修理 工具",
        "💡": "灯泡 lightbulb 电灯 灯",
        "🪑": "椅子 chair 凳子",
        "🧹": "扫帚 broom 打扫 清洁",
        "🚪": "门 door",
        "🔑": "钥匙 key",
        "🌿": "绿叶 leaf 植物 绿植",
        "🏡": "花园洋房 house 花园 小屋",
        "🏢": "办公楼 office 写字楼 大楼",
        "🏘️": "街区 houses 房屋 小区",
        "🛁": "浴缸 bathtub 洗澡 浴室",
        "🧻": "纸巾 toilet paper 卫生纸 抽纸",
        "🪟": "窗户 window 窗",
        "🛎️": "服务铃 bell 铃铛 前台",
        "🧺": "篮子 basket 洗衣篮 收纳",
        "🕯️": "蜡烛 candle 香薰",
        "🪴": "盆栽 potted plant 植物 花盆 绿植",
        "🗄️": "文件柜 cabinet 柜子 抽屉",
        // 数码
        "📱": "手机 phone mobile 智能手机",
        "💻": "电脑 laptop 笔记本 计算机",
        "⌚": "手表 watch 智能手表",
        "🎧": "耳机 headphone 耳麦",
        "📷": "相机 camera 拍照 照相机",
        "🖥️": "台式电脑 desktop 显示器 电脑",
        "🖱️": "鼠标 mouse",
        "⌨️": "键盘 keyboard",
        "🖨️": "打印机 printer 打印",
        "📺": "电视 tv television",
        "📻": "收音机 radio",
        "📸": "相机 camera 拍照",
        "🎙️": "麦克风 microphone 话筒 录音",
        "🔋": "电池 battery 电量 充电",
        "🔌": "插头 plug 电源 充电 插座",
        "🤖": "机器人 robot ai",
        // 娱乐
        "🎬": "场记板 movie 电影 开机",
        "🎮": "游戏手柄 game 游戏 电玩",
        "🎤": "麦克风 microphone 唱歌 ktv",
        "🎫": "票 ticket 门票 演出票",
        "🎸": "吉他 guitar 音乐",
        "🎪": "马戏团 circus",
        "🎨": "调色板 art 绘画 画画 美术",
        "🎡": "摩天轮 ferris wheel 游乐园",
        "🎭": "面具 theater 戏剧 剧院",
        "🎰": "老虎机 slot machine 赌场",
        "🎳": "保龄球 bowling",
        "🎲": "骰子 dice 掷骰 游戏",
        "🧸": "玩具熊 teddy bear 玩具 娃娃",
        "🎢": "过山车 roller coaster 游乐园",
        "🎠": "旋转木马 carousel 游乐园",
        "🎼": "乐谱 musical score 曲谱 音乐",
        "🎹": "钢琴 piano",
        "🥁": "鼓 drum 架子鼓",
        "🎺": "小号 trumpet 喇叭 铜管",
        "🎻": "小提琴 violin 弦乐",
        // 运动
        "⚽": "足球 soccer football",
        "🏀": "篮球 basketball",
        "🏋️": "举重 weightlifting 健身 健身房",
        "🎯": "靶心 dart 目标 射击",
        "⛷️": "滑雪 skiing 滑雪者",
        "🏊": "游泳 swimming 游泳者",
        "⚾": "棒球 baseball",
        "🎾": "网球 tennis",
        "🏐": "排球 volleyball",
        "🏓": "乒乓球 ping pong table tennis",
        "🥊": "拳击 boxing 拳套",
        "🥋": "武道 martial arts 跆拳道 柔道 空手道",
        "⛳": "高尔夫 golf",
        "🏄": "冲浪 surfing",
        "🚴": "骑行 cycling 骑车 自行车",
        "🏃": "跑步 running 奔跑",
        "🧗": "攀岩 climbing 攀登",
        "🤿": "潜水 diving 潜水面镜",
        "🛹": "滑板 skateboard",
        "🏸": "羽毛球 badminton",
        // 健康
        "🩺": "听诊器 stethoscope 医生 看病",
        "💊": "药丸 pill 药 胶囊 吃药",
        "🏥": "医院 hospital",
        "🦷": "牙齿 tooth 牙科 看牙",
        "👀": "眼睛 eyes 眼科",
        "🚑": "救护车 ambulance 急救",
        "💉": "注射器 syringe 打针 输液 疫苗",
        "🩹": "创可贴 bandage 创口贴 绷带",
        "🧘": "冥想 yoga 瑜伽 打坐",
        "🌡️": "体温计 thermometer 发烧 温度计",
        "🦴": "骨头 bone 骨骼",
        "🦠": "细菌 microbe 病毒 病菌",
        "🧬": "基因 dna 遗传",
        "🩸": "血 drop 血液 献血",
        "🫀": "心脏 heart 器官",
        "🫁": "肺 lungs 呼吸 器官",
        "🧠": "大脑 brain 脑子 头脑",
        "👂": "耳朵 ear 听力",
        "👄": "嘴唇 mouth lips 嘴",
        "💆": "按摩 massage 头部按摩 放松",
        // 教育
        "📚": "书 books 读书 学习 书籍",
        "✏️": "铅笔 pencil 写字",
        "🎓": "毕业帽 graduation cap 毕业 学位 学士帽",
        "🧩": "拼图 puzzle",
        "🖍️": "蜡笔 crayon 涂色",
        "📐": "三角尺 ruler 三角板 尺子",
        "🔬": "显微镜 microscope 实验",
        "🗒️": "记事本 notepad 便签 笔记本",
        "📓": "笔记本 notebook 本子",
        "📖": "打开的书 open book 读书 阅读",
        "📰": "报纸 newspaper 新闻",
        "🖊️": "钢笔 pen 签字笔",
        "✂️": "剪刀 scissors 剪",
        "📏": "直尺 ruler 尺子",
        "🔭": "望远镜 telescope 天文",
        "🧪": "试管 test tube 实验 化学",
        "📒": "记账本 ledger notebook 记账 本子",
        // 宠物
        "🐾": "爪印 paw 脚印 动物",
        "🐶": "狗 dog 小狗 狗狗",
        "🐱": "猫 cat 小猫 猫咪",
        "🐟": "鱼 fish 金鱼",
        "🐦": "鸟 bird 小鸟",
        "🐢": "乌龟 turtle",
        "🐰": "兔子 rabbit 小兔",
        "🐹": "仓鼠 hamster",
        "🐭": "老鼠 mouse 耗子",
        "🐮": "奶牛 cow 牛",
        "🐷": "猪 pig 小猪",
        "🐸": "青蛙 frog",
        "🐔": "鸡 chicken 母鸡",
        "🦜": "鹦鹉 parrot",
        "🦎": "蜥蜴 lizard 壁虎",
        "🐍": "蛇 snake",
        // 收入金融
        "💼": "公文包 briefcase 工作 上班 商务",
        "🏆": "奖杯 trophy 奖 奖励 冠军",
        "🌙": "月亮 moon 晚上 夜班",
        "🧧": "红包 red envelope 压岁钱",
        "🧑‍💻": "程序员 technologist 工作 上班族 电脑办公",
        "🚀": "火箭 rocket 创业 起飞",
        "📈": "上涨趋势 chart up 涨 增长 投资收益",
        "🎉": "礼花筒 party popper 庆祝 派对",
        "✨": "闪光 sparkles 闪 亮",
        "🤑": "发财 money face 见钱眼开",
        "💹": "上涨 chart 投资收益 股票涨",
        "📊": "柱状图 bar chart 数据 报表",
        "💸": "花钱 money with wings 消费 流失",
        "🏅": "奖牌 medal 勋章",
        "🥇": "金牌 gold medal 第一 冠军",
        // 其他
        "⚖️": "天平 balance 平衡 公平",
        "⭐": "星星 star",
        "🌟": "闪亮星 glowing star 发光 闪",
        "🔥": "火 fire flame 热门",
        "🌈": "彩虹 rainbow",
        "❤️": "红心 heart 爱 喜欢",
        "🎈": "气球 balloon 生日 派对",
        "🕐": "时钟 clock 时间 一点",
        "📌": "图钉 pin 标记 固定",
        "🌍": "地球 earth globe 世界",
        "❄️": "雪花 snow 冬天 冷",
        "☀️": "太阳 sun 晴天 阳光",
        "🌊": "浪花 wave 海浪 大海",
        "🍀": "四叶草 clover 幸运",
        "🌸": "樱花 blossom 花朵 春天",
        "🌺": "花朵 hibiscus 花",
        "🌻": "向日葵 sunflower 花",
        "🌴": "棕榈树 palm tree 海滩 度假",
        "⛰️": "山 mountain 登山",
        "🔔": "铃铛 bell 提醒 通知",
    ]

    static func normalized(_ query: String) -> String {
        query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }

    /// A query matches via the icon's keywords or the group title it sits
    /// under (so a group name filters the whole group).
    static func matches(_ emoji: String, query: String, groupTitle: String) -> Bool {
        let q = normalized(query)
        guard !q.isEmpty else { return true }
        if groupTitle.lowercased().contains(q) { return true }
        return keywords[emoji]?.lowercased().contains(q) ?? false
    }
}
