#!/usr/bin/env node
// Generates one nginx location-block file per app — derived from the root
// manifest.json — into an output directory (defaults to scripts/nginx/apps;
// assemble.sh points it at the tarball's nginx/apps/).
//
// The emitted files are self-contained: each `location` inlines its proxy
// headers, so there are NO nested `include`s and NO hard-coded absolute paths.
// The only absolute path in the whole setup is the single `include` line the
// operator adds once to their TLS server block (see server-block.example.conf).
//
//   node scripts/gen-nginx.mjs [outDir]
//
// Adding an app = adding it to manifest.json. nginx + PM2 + the tarball then
// stay in lockstep (ecosystem.config.js and assemble.sh derive from the same
// source).

import {
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(
  readFileSync(join(here, "..", "manifest.json"), "utf8"),
);
const apps = manifest.apps;
const outDir = process.argv[2] ?? join(here, "nginx", "apps");

mkdirSync(outDir, { recursive: true });
// Drop stale generated confs (e.g. an app removed from manifest.json).
for (const f of readdirSync(outDir)) {
  if (f.endsWith(".conf")) unlinkSync(join(outDir, f));
}

const BANNER =
  "# AUTO-GENERATED by scripts/gen-nginx.mjs from manifest.json — do not edit by hand.";

const COMMON_HEADERS = [
  "    proxy_http_version 1.1;",
  "    proxy_set_header Host $host;",
  "    proxy_set_header X-Real-IP $remote_addr;",
  "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
  "    proxy_set_header X-Forwarded-Proto $scheme;",
];
const WS_HEADERS = [
  "    proxy_set_header Upgrade $http_upgrade;",
  '    proxy_set_header Connection "upgrade";',
];

function block({ location, port, websocket }) {
  const lines = [`location ${location} {`];
  lines.push(`    proxy_pass http://127.0.0.1:${port};`);
  lines.push(...COMMON_HEADERS);
  if (websocket) lines.push(...WS_HEADERS);
  lines.push("}");
  return lines.join("\n");
}

for (const app of apps) {
  const chunks = [BANNER, ""];
  if (app.name === "gateway") {
    // Catch-all: shortest prefix, so nginx uses it as the fallback for /api and /.
    chunks.push("# Gateway: catch-all for /api (Hono) + the root page.");
    chunks.push(block({ location: "/", port: app.port, websocket: true }));
  } else {
    if (!app.basePath || !app.assetPrefix) {
      throw new Error(`App "${app.name}" is missing basePath/assetPrefix.`);
    }
    chunks.push(
      `# ${app.name}: static assets (assetPrefix ${app.assetPrefix}).`,
    );
    chunks.push(
      block({
        location: `${app.assetPrefix}/`,
        port: app.port,
        websocket: false,
      }),
    );
    chunks.push("");
    chunks.push(`# ${app.name}: app (basePath ${app.basePath}).`);
    chunks.push(
      block({ location: app.basePath, port: app.port, websocket: true }),
    );
  }
  chunks.push("");
  writeFileSync(join(outDir, `${app.name}.conf`), `${chunks.join("\n")}\n`);
}

console.log(`==> Generated ${apps.length} nginx app conf(s) into ${outDir}`);
