// Generates packages/shared/src/version.ts from the git repo or CI env.
//
// Precedence for the version string:
//   1. APP_VERSION env  (set by CI from the git tag, e.g. "v1.2.3")
//   2. `git describe --tags --always --dirty` (nearest tag, or short sha)
//   3. "v0.0.0-unknown" fallback when git is unavailable
//
// Run automatically via the root package `prepare`, `predev`, and `prebuild`
// lifecycle hooks, so the file always exists for bundlers and editors.

import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outFile = resolve(root, "packages/shared/src/version.ts");

function run(cmd) {
  try {
    return execSync(cmd, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

const envVersion = process.env.APP_VERSION?.trim();
let version = envVersion;
if (!version) {
  const described = run("git describe --tags --always --dirty");
  version = described
    ? described.startsWith("v")
      ? described
      : `v${described}`
    : "v0.0.0-unknown";
}

const gitSha =
  process.env.APP_GIT_SHA?.trim() ||
  run("git rev-parse --short HEAD") ||
  "unknown";

const buildTime = process.env.BUILD_TIME?.trim() || new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_GIT_SHA = ${JSON.stringify(gitSha)};
export const APP_BUILD_TIME = ${JSON.stringify(buildTime)};
`;

let existing = null;
try {
  existing = readFileSync(outFile, "utf8");
} catch {
  // not generated yet
}

if (existing !== content) {
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, content);
  console.log(`[gen-version] wrote ${version} @ ${gitSha}`);
} else {
  console.log(`[gen-version] up-to-date (${version})`);
}
